apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: postgresql-dev
  labels:
    app: postgres
spec:
  type: LoadBalancer
  selector:
    app: postgres
  ports:
    - protocol: TCP
      name: http
      port: 5432
      targetPort: 5432
  externalIPs:
    - 192.168.0.216

