bases:
  - ../../application

patches:
  - replica_count.yaml
  - resource_limits.yaml

configMapGenerator:
- name: example-config
  namespace: example
  behavior: replace
  files:
    - config/config.json

patchesStrategicMerge:
  - env.yaml
